interface ICollektiveEngine
{
    List<NodeState> Step(List<SensorData> sensing);
    void UpdateTopology(Topology topology);
    void UpdateGlobalData(GlobalData globalData);
}

// generated by Google.FlatBuffers
record AggregateNode(int Id, SensorData SensorData, NodeState State);

record Topology(List<Set<int>> AdjacencyList);

record GlobalData(int TotalNodes, double DeltaTime, CustomGlobalData CustomData);

// done by the user with Google.FlatBuffers
interface NodeState;

interface SensorData;

interface CustomGlobalData;
