interface CollektiveEngine(initialState: List<NodeState>)
{
    fun step(sensing: List<SensorData>): List<NodeState>
    fun updateTopology(topology: Topology): Unit
    fun updateGlobalData(globalData: GlobalData): Unit
}

// generated by Google.FlatBuffers
data class AggregateNode(val id: Int, val sensorData: SensorData, val state: NodeState);
data class Topology(val adjacencyList: List<Set<Int>>);
data class GlobalData(val totalNodes: Int, val deltaTime: Double, val customData: CustomGlobalData);

// impl by the user with Google.FlatBuffers
interface NodeState;
interface SensorData;
interface CustomGlobalData;

// impl by the user with Collektive
fun Aggregate<Int>.entrypoint(sensorData: SensorData): NodeState;
